package de.schliweb.bluesharpbendingapp.view.android;
/*
 * Copyright (c) 2023 Christian Kierdorf
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the “Software”),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */

import android.content.Context;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProvider;
import de.schliweb.bluesharpbendingapp.R;
import de.schliweb.bluesharpbendingapp.databinding.FragmentAboutBinding;
import de.schliweb.bluesharpbendingapp.utils.LoggingUtils;
import de.schliweb.bluesharpbendingapp.view.AboutView;


/**
 * AboutFragment is a fragment class that represents the "About" section of the application.
 * It displays version-related information of the application, such as version name and version code.
 * This class implements the AboutView and FragmentView interfaces and provides callbacks for
 * handling creation, destruction, and view lifecycle events.
 * <p>
 * Key operations:
 * - Inflates the layout using a view binding to ensure UI elements are interactable.
 * - Retrieves and displays application version name and version code from PackageManager.
 * - Notifies a shared ViewModel about the current fragment for communication or state management.
 */
public class AboutFragment extends Fragment implements AboutView, FragmentView {


    /**
     * This variable holds an instance of FragmentAboutBinding, which is generated by Android's View Binding library.
     * It is used to interact with the views defined in the corresponding XML layout file for the AboutFragment class.
     * <p>
     * Key points:
     * - Provides a type-safe way to access views in the layout.
     * - Initialized during the fragment's onCreateView lifecycle method using the binding's inflate method.
     * - Must be set to null in the onDestroyView lifecycle method to avoid memory leaks.
     */
    private FragmentAboutBinding binding;


    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        binding = FragmentAboutBinding.inflate(inflater, container, false);
        return binding.getRoot();

    }


    /**
     * Called when the fragment's view has been created.
     * This method is used to display version information of the application
     * and to initialize the shared ViewModel with the current fragment for fragment selection.
     *
     * @param view               The View returned by {@code onCreateView}.
     * @param savedInstanceState If non-null, this fragment is being re-constructed from a
     *                           previous saved state as given here.
     */
    @Override
    public void onViewCreated(@NonNull View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        try {
            Context context = getContext();
            assert context != null;
            String versionName = context.getPackageManager().getPackageInfo(context.getPackageName(), 0).versionName;
            long versionCode = context.getPackageManager().getPackageInfo(context.getPackageName(), 0).getLongVersionCode();
            TextView textView = binding.aboutVersion;
            textView.setText(getString(R.string.about_version, versionName, versionCode));
        } catch (PackageManager.NameNotFoundException e) {
            LoggingUtils.logError("Failed to get package information", e);
        }

        FragmentViewModel viewModel = new ViewModelProvider(requireActivity()).get(FragmentViewModel.class);
        viewModel.selectFragmentView(this);
    }


    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }


    @Override
    public Object getInstance() {
        return this;
    }
}
