package de.schliweb.bluesharpbendingapp.view.desktop;
/*
 * Copyright (c) 2023 Christian Kierdorf
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the “Software”),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import de.schliweb.bluesharpbendingapp.controller.TrainingContainer;
import de.schliweb.bluesharpbendingapp.controller.TrainingViewHandler;
import de.schliweb.bluesharpbendingapp.view.HarpViewNoteElement;
import de.schliweb.bluesharpbendingapp.view.TrainingView;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ItemEvent;

/**
 * The type Training view desktop.
 */
public class TrainingViewDesktop implements TrainingView {
    /**
     * The Content pane.
     */
    private JPanel contentPane;
    /**
     * The Start button.
     */
    private JButton startButton;
    /**
     * The Label trainings.
     */
    private JLabel labelTrainings;
    /**
     * The Combo trainings.
     */
    private JComboBox<String> comboTrainings;
    /**
     * The Label percentage.
     */
    private JLabel labelPercentage;
    /**
     * The Content pane header.
     */
    private JPanel contentPaneHeader;
    /**
     * The Content pane footer.
     */
    private JPanel contentPaneFooter;
    /**
     * The Stop button.
     */
    private JButton stopButton;
    /**
     * The Content pane main.
     */
    private JPanel contentPaneMain;
    /**
     * The Actual note.
     */
    private JPanel actualNote;
    /**
     * The Progress bar.
     */
    private JProgressBar progressBar;
    /**
     * The Label precision.
     */
    private JLabel labelPrecision;
    /**
     * The Combo precision.
     */
    private JComboBox<String> comboPrecision;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Instantiates a new Training view desktop.
     */
    public TrainingViewDesktop() {
        stopButton.setEnabled(false);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPaneHeader = new JPanel();
        contentPaneHeader.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentPaneHeader, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelTrainings = new JLabel();
        labelTrainings.setText("Trainings");
        contentPaneHeader.add(labelTrainings, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboTrainings = new JComboBox();
        contentPaneHeader.add(comboTrainings, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelPercentage = new JLabel();
        labelPercentage.setText("Progress");
        contentPaneHeader.add(labelPercentage, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        progressBar = new JProgressBar();
        progressBar.setStringPainted(true);
        contentPaneHeader.add(progressBar, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelPrecision = new JLabel();
        labelPrecision.setText("Precision");
        contentPaneHeader.add(labelPrecision, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        comboPrecision = new JComboBox();
        contentPaneHeader.add(comboPrecision, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contentPaneFooter = new JPanel();
        contentPaneFooter.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentPaneFooter, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        startButton = new JButton();
        startButton.setText("Start");
        contentPaneFooter.add(startButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stopButton = new JButton();
        stopButton.setText("Stop");
        stopButton.setVerticalAlignment(0);
        contentPaneFooter.add(stopButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contentPaneMain = new JPanel();
        contentPaneMain.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(contentPaneMain, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        actualNote = new JPanel();
        actualNote.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        actualNote.setBackground(new Color(-6513759));
        contentPaneMain.add(actualNote, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        actualNote.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
    }

    /**
     * $$$ get root component $$$ j component.
     *
     * @return the j component
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    @Override
    public void setTrainings(String[] trainings) {
        comboTrainings.setModel(new DefaultComboBoxModel<>(trainings));
    }

    @Override
    public void setPrecisions(String[] precisions) {
        comboPrecision.setModel(new DefaultComboBoxModel<>(precisions));
    }

    @Override
    public void setSelectedTraining(int selectedTrainingIndex) {
        comboTrainings.getModel().setSelectedItem(comboTrainings.getModel().getElementAt(selectedTrainingIndex));
    }

    @Override
    public void setSelectedPrecision(int selectedPrecisionIndex) {
        comboPrecision.getModel().setSelectedItem(comboPrecision.getModel().getElementAt(selectedPrecisionIndex));
    }

    @Override
    public HarpViewNoteElement getActualHarpViewElement() {
        return HarpViewNoteElementDesktop.getInstance(actualNote);
    }

    @Override
    public void initTrainingContainer(TrainingContainer trainingContainer) {
        HarpViewNoteElementDesktop actualNoteElementDesktop = HarpViewNoteElementDesktop.getInstance(actualNote);
        actualNoteElementDesktop.setColor(actualNote.getBackground());
        actualNoteElementDesktop.setNoteName(trainingContainer.getActualNoteName() != null ? trainingContainer.getActualNoteName() : "");
        progressBar.setValue(trainingContainer.getProgress());
        actualNoteElementDesktop.clear();
    }

    @Override
    public void toggleButton() {
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
    }

    /**
     * Add training view handler.
     *
     * @param trainingViewHandler the training view handler
     */
    public void addTrainingViewHandler(TrainingViewHandler trainingViewHandler) {
        comboTrainings.addItemListener(event -> {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                trainingViewHandler.handleTrainingSelection(comboTrainings.getSelectedIndex());
            }
        });
        comboPrecision.addItemListener(event -> {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                trainingViewHandler.handlePrecisionSelection(comboPrecision.getSelectedIndex());
            }
        });
        startButton.addActionListener(event -> {
            if (event.getSource() == startButton) {
                trainingViewHandler.handleTrainingStart();
                stopButton.setEnabled(true);
                startButton.setEnabled(false);
            }
        });
        stopButton.addActionListener(event -> {
            if (event.getSource() == stopButton) {
                trainingViewHandler.handleTrainingStop();
                startButton.setEnabled(true);
                stopButton.setEnabled(false);
            }
        });
    }

}
