name: Build & Release with jpackage

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v1.2.3, etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Run jpackage in :desktop
        run: ./gradlew :desktop:jpackage
        env:
          GRADLE_OPTS: "-Dhttp.socketTimeout=30000 -Dhttp.connectionTimeout=30000"

      - name: Upload installer to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: desktop/build/jpackage/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload installer as GitHub Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-installer-${{ runner.os }}
          path: desktop/build/jpackage/
